name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: MacOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: make test

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: make test-linux

  static-stdlib:
    name: Static standard library
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.8.0'
      - name: Install dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev
      - uses: actions/checkout@v3
      - name: Build for static-stdlib
        run: make build-for-static-stdlib

  wasm:
     name: SwiftWASM
     runs-on: ubuntu-latest
     strategy:
       matrix:
         include:
           - { toolchain: wasm-5.6.0-RELEASE }

     steps:
       - uses: actions/checkout@v3
       - run: echo "${{ matrix.toolchain }}" > .swift-version
       - uses: swiftwasm/swiftwasm-action@v5.6
         with:
           shell-action: swift build
